*Think Linear Algebra* is not for sale yet, but if you would like to support this project, you can [buy me a coffee](https://buymeacoffee.com/allendowney).

# Title



[Click here to run this notebook on Colab](https://colab.research.google.com/github/AllenDowney/ThinkLinearAlgebra/blob/main/nb/track.ipynb).

In [64]:
from os.path import basename, exists


def download(url):
    filename = basename(url)
    if not exists(filename):
        from urllib.request import urlretrieve

        local, _ = urlretrieve(url, filename)
        print("Downloaded " + local)


download("https://github.com/AllenDowney/ThinkLinearAlgebra/raw/main/utils.py")

In [65]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from utils import decorate

In [123]:
import sympy as sp

C2H5OH = sp.Symbol('C_{2} H_5 OH')
O2 = sp.Symbol('O2')
CO2 = sp.Symbol('CO2')
H2O = sp.Symbol('H_{2} O')

In [124]:
lhs = C2H5OH + O2
rhs = CO2 + H2O
lhs

C_{2} H_5 OH + O2

In [125]:
from IPython.display import display, Math

# Use LaTeX to display with reaction arrow
display(Math(f"{lhs} \\rightarrow {rhs}"))

<IPython.core.display.Math object>

In [126]:
# Define symbols for the unknown coefficients
x1, x2, x3, x4 = sp.symbols('x1 x2 x3 x4')

In [127]:
# Write the unbalanced equation symbolically
lhs = x1 * C2H5OH + x2 * O2
rhs = x3 * CO2 + x4 * H2O

In [128]:
reaction = sp.Eq(lhs, rhs)
reaction

Eq(C_{2} H_5 OH*x1 + O2*x2, CO2*x3 + H_{2} O*x4)

Carbon: 2 from ethanol = 1 per CO2

In [129]:
eq_carbon = sp.Eq(2*x1, x3)         
eq_carbon

Eq(2*x1, x3)

Hydrogen: 6 from ethanol = 2 per H2O

In [130]:
eq_hydrogen = sp.Eq(6*x1, 2*x4)     
eq_hydrogen

Eq(6*x1, 2*x4)

Oxygen: 1 in ethanol + 2 per O2 = 2 per CO2 + 1 per H2O

In [131]:
eq_oxygen = sp.Eq(x1 + 2*x2, 2*x3 + x4)  
eq_oxygen

Eq(x1 + 2*x2, 2*x3 + x4)

In [132]:
A, b = sp.linear_eq_to_matrix([eq_carbon, eq_hydrogen, eq_oxygen], (x1, x2, x3, x4))
A

Matrix([
[2, 0, -1,  0],
[6, 0,  0, -2],
[1, 2, -2, -1]])

In [133]:
b

Matrix([
[0],
[0],
[0]])

In [134]:
nullspace = A.nullspace()
len(nullspace)

1

In [135]:
basis_vector = nullspace[0]
basis_vector

Matrix([
[1/3],
[  1],
[2/3],
[  1]])

In [136]:
denoms = [sp.denom(term) for term in basis_vector]
lcm = sp.lcm(denoms)
lcm

3

In [137]:
solution = basis_vector * lcm
solution

Matrix([
[1],
[3],
[2],
[3]])

In [138]:
A * solution

Matrix([
[0],
[0],
[0]])

In [139]:

A = np.array(A).astype(float)
A

array([[ 2.,  0., -1.,  0.],
       [ 6.,  0.,  0., -2.],
       [ 1.,  2., -2., -1.]])

In [140]:
from scipy.linalg import null_space

ns = null_space(A)
ns

array([[0.20851441],
       [0.62554324],
       [0.41702883],
       [0.62554324]])

In [141]:
vec = ns.T[0]
vec

array([0.20851441, 0.62554324, 0.41702883, 0.62554324])

In [143]:
vec @ vec

np.float64(0.9999999999999999)

In [142]:
denom = np.min(np.abs(vec[vec != 0]))
scaled = vec / denom
scaled

array([1., 3., 2., 3.])

### Exercise

Balance the equation for the combustion of methanol.

In [109]:
CH3OH = sp.Symbol('C H_{3} OH')

In [110]:
lhs = x1 * CH3OH + x2 * O2
rhs = x3 * CO2 + x4 * H2O

In [111]:
reaction = sp.Eq(lhs, rhs)
reaction

Eq(C H_{3} OH*x1 + O2*x2, CO2*x3 + H_{2} O*x4)

In [112]:
eq_carbon = sp.Eq(x1, x3)         
eq_carbon

Eq(x1, x3)

Hydrogen: 6 from ethanol = 2 per H2O

In [113]:
eq_hydrogen = sp.Eq(4*x1, 2*x4)     
eq_hydrogen

Eq(4*x1, 2*x4)

Oxygen: 1 in ethanol + 2 per O2 = 2 per CO2 + 1 per H2O

In [114]:
eq_oxygen = sp.Eq(x1 + 2*x2, 2*x3 + x4)  
eq_oxygen

Eq(x1 + 2*x2, 2*x3 + x4)

In [115]:
A, b = sp.linear_eq_to_matrix([eq_carbon, eq_hydrogen, eq_oxygen], (x1, x2, x3, x4))
A

Matrix([
[1, 0, -1,  0],
[4, 0,  0, -2],
[1, 2, -2, -1]])

In [116]:
b

Matrix([
[0],
[0],
[0]])

In [117]:
nullspace = A.nullspace()
len(nullspace)

1

In [118]:
basis_vector = nullspace[0]
basis_vector

Matrix([
[1/2],
[3/4],
[1/2],
[  1]])

In [119]:
denoms = [sp.denom(term) for term in basis_vector]
lcm = sp.lcm(denoms)
lcm

4

In [120]:
solution = basis_vector * lcm
solution

Matrix([
[2],
[3],
[2],
[4]])

[Think Linear Algebra](https://allendowney.github.io/ThinkLinearAlgebra/index.html)

Copyright 2025 [Allen B. Downey](https://allendowney.com)

Code license: [MIT License](https://mit-license.org/)

Text license: [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/)